### ISSUE TITLE
Tests failing after 442bd9f57fdc7f186e34958ac422fa39eadf03c2

### ISSUE THREAD

**Issue by sli2126** [googleapis/python-dlp#18]
Arguments are out of sync.

#### Steps to reproduce

  1. run tests in test_system_dlp_service_v2_vpcsc.py

#### Stack trace
```
     def test_create_inspect_template_inside(client, name_inside):
>       client.create_inspect_template(name_inside)  # no perms issue
E       TypeError: create_inspect_template() missing 1 required positional argument: 'inspect_template'

    def test_create_inspect_template_outside(client, name_outside):
        with pytest.raises(exceptions.PermissionDenied) as exc:
>           client.create_inspect_template(name_outside)
E           TypeError: create_inspect_template() missing 1 required positional argument: 'inspect_template'

    def test_create_deidentify_template_inside(client, name_inside):
>       client.create_deidentify_template(name_inside)
E       TypeError: create_deidentify_template() missing 1 required positional argument: 'deidentify_template'

    def test_create_deidentify_template_outside(client, name_outside):
        with pytest.raises(exceptions.PermissionDenied) as exc:
>           client.create_deidentify_template(name_outside)
E           TypeError: create_deidentify_template() missing 1 required positional argument: 'deidentify_template'

    def test_create_job_trigger_inside(client, name_inside):
        with pytest.raises(exceptions.InvalidArgument):  # no perms issue
>           client.create_job_trigger(name_inside)
E           TypeError: create_job_trigger() missing 1 required positional argument: 'job_trigger'

    def test_create_job_trigger_outside(client, name_outside):
        with pytest.raises(exceptions.PermissionDenied) as exc:
>           client.create_job_trigger(name_outside)
E           TypeError: create_job_trigger() missing 1 required positional argument: 'job_trigger'

    def test_create_stored_info_type_inside(client, name_inside):
        with pytest.raises(exceptions.InvalidArgument):  # no perms issue
>           client.create_stored_info_type(name_inside)
E           TypeError: create_stored_info_type() missing 1 required positional argument: 'config'

    def test_create_stored_info_type_outside(client, name_outside):
        with pytest.raises(exceptions.PermissionDenied) as exc:
>           client.create_stored_info_type(name_outside)
E           TypeError: create_stored_info_type() missing 1 required positional argument: 'config'
```
